workspace:
  base: /go/src
  path: github.com/appleboy/com

pipeline:
  test:
    image: appleboy/golang-testing
    pull: true
    commands:
      - make install
      - make vet
      - make lint
      - coverage all
      - make coverage
    when:
      event: [ push, tag, pull_request ]
