workspace:
  base: /go/src
  path: github.com/appleboy/com

pipeline:
  test:
    image: appleboy/golang-testing
    pull: true
    commands:
      - make install
      - make vet
      - make lint
      - coverage all
    when:
      event: [ push, pull_request ]

  codecov:
    image: robertstettner/drone-codecov
    group: build
    secrets: [ codecov_token ]
    files:
      - .cover/coverage.txt
    when:
      event: [ push, pull_request ]

  discord:
    image: appleboy/drone-discord
    pull: true
    secrets: [ discord_webhook_id, discord_webhook_token ]
    when:
      status: [ changed, failure ]
