workspace:
  base: /go
  path: src/github.com/appleboy/com

pipeline:
  test:
    image: appleboy/golang-testing:${GO_VERSION}
    pull: true
    commands:
      - make install
      - make vet
      - make lint
      - coverage all
      # send coverage report
      - curl -s https://codecov.io/bash > .codecov &&
        chmod +x .codecov &&
        ./.codecov -t ${CODECOV_TOKEN} -f .cover/coverage.txt
    when:
      event: [ push, tag, pull_request ]
      matrix:
        GO_VERSION: 1.7.4
matrix:
  GO_VERSION:
    - 1.7.4
    - 1.6.4
