workspace:
  base: /go
  path: src/github.com/appleboy/com

pipeline:
  test:
    image: appleboy/golang-testing
    pull: true
    commands:
      - make install
      - make vet
      - make lint
      - make test
    when:
      event: [ push, tag, pull_request ]
