---
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: test
  pull: always
  image: golang:1.11
  commands:
  - make vet
  - make lint
  - coverage all

- name: codecov
  pull: default
  image: robertstettner/drone-codecov
  settings:
    files:
    - .cover/coverage.txt
    group: build
  environment:
    CODECOV_TOKEN:
      from_secret: codecov_token
  when:
    event:
    - push
    - pull_request

- name: discord
  pull: always
  image: appleboy/drone-discord
  environment:
    DISCORD_WEBHOOK_ID:
      from_secret: discord_webhook_id
    DISCORD_WEBHOOK_TOKEN:
      from_secret: discord_webhook_token
  when:
    status:
    - changed
    - failure

...
